[project]
name = "dovicrop"
version = "0.2.3"
description = "CLI to properly crop RPU's extracted via dovi_tool"
authors = [{ name = "Jessie Wilson" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = ["ruff>=0.14"]
build = ["pyinstaller", "pyinstaller-hooks-contrib>=2024.0,<2025"]

[tool.uv]
package = false

[tool.uv.sources]
pyinstaller = { path = "custom-pyinstaller", editable = true }

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
